##===- runtime/FunctionTracingRuntime/Makefile ------------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#

LEVEL=../..

#
# List all of the subdirectories that we will compile.
#
DIRS= CallEdgeTracing CallSiteTracing BurstyCallSiteTracing AdvCallSiteTracing FineCallSiteTracing AWCallSiteTracing BasicBlockCallSiteTracing

include $(LEVEL)/Makefile.common

