##===- lib/Makefile/Tracing ------------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=../..

#
# List all of the subdirectories that we will compile.
#
DIRS=CallSiteTracing CallEdgeTracing

include $(LEVEL)/Makefile.common
